### PR TITLE
Version 3.0

### PR DESCRIPTION
**Pull request by frasmage**

### CODE REVIEW

**Comment by frasmage** [comment]
hmm, can't seem to figure out why the localUrlGenerator is failing in Travis on Laravel 6.0. I can't replicate that failure locally.

**Comment by frasmage** [comment]
I will leave this open for a few more days, in case anyone else has proposals for other breaking changes to include in the major version push. I will merge this by Sunday if there is nothing outstanding.

**Comment by sebdesign** [comment]
Great! I'll try the 3.0 branch and let you know how it goes.

**Comment by hasnatbabur** [comment]
@frasmage Any update on Laravel 6 fix please? Actually we are waiting for the update highly! Thanks.

**Pull request merged**
