### PR TITLE
Add cascade of (soft) deletes of mediable models

### PR DESCRIPTION
**Pull request by Riesjart**
Detach associated media when mediable model is (soft) deleted.

### CODE REVIEW

**Comment by frasmage** [comment]
Hi @Riesjart, 

I really like the idea of this PR, that is something I hadn't thought of. I think it could use a little bit more fleshing out. 

I can think of a couple more cases to be accounted for:
- if model has no key/id (i.e. doesn't exist and no id manually assigned), it can't be attached to anything in the first place.
- if model is using softDeletes, should check your config variable first.
- if model is not using softDeletes, should always cascade.
- We should probably also check if the Media model is implementing softDeletes as well and cascade the relationship if necessary.

Since this behaviour is destructive, it definitely needs tests written for it before it can be merged into master. 

I'm hoping to have some time to help with this over the weekend.

**Comment by Riesjart** [comment]
Hi @frasmage,

Thank you for building this very usefull package, and picking up this PR. I see you have already merged the PR, but I would still like to reply on your cases:

- if model has no key/id (i.e. doesn't exist and no id manually assigned), it can't be attached to anything in the first place.
**There would be no problem here, since the Eloquent 'deleted' event would not be fired on the model in that case.**

-if model is using softDeletes, should check your config variable first.
**The PR already provides this. ($model->exists will be true when soft deleted) **

-if model is not using softDeletes, should always cascade.
** The PR already provides this. ($model->exists will be true when soft deleted) **

* We should probably also check if the Media model is implementing softDeletes as well and cascade the relationship if necessary.
** Why would you want to delete a Media model by default in that case? For example, the Media model can still be related to other Mediable models, has to be available for future attachment of (other) Mediable models, or has other functions/relations not related to a Mediable model at all **

**Comment by frasmage** [comment]
Oh I see, hadn't realized the relationship between `SoftDeletes` and `exists`. That is probably cleaner than my approach, I'll see about working that back into the solution.

>Why would you want to delete a Media model by default in that case? For example, the Media model can still be related to other Mediable models, has to be available for future attachment of (other) Mediable models, or has other functions/relations not related to a Mediable model at all

Not delete the media model, only cascade the _relationships_ (i.e. mediables pivot table) if either the Mediable model or the Media itself is soft deleted. As in, while trashed, don't maintain any relationships until it is restored.

**Comment by Riesjart** [comment]
I need to get back on the 'exists' property. Just found that the exists-property has value false after soft-deleting, just like hard-deleted models. Only when retrieving a soft-deleted (trashed) model from the database, the exists-property has value true. My mistake. Luckily, you have implemented your own better approach.

> Not delete the media model, only cascade the relationships (i.e. mediables pivot table) if either the Mediable model or the Media itself is soft deleted. As in, while trashed, don't maintain any relationships until it is restored.

Ah I see. Good to see you have implemented this in the Media model too.

**Pull request merged**
