### PR TITLE
Use file content hash has filename if none is set.

### PR DESCRIPTION
**Pull request by geidelguerra**

### CODE REVIEW

**Comment by frasmage** [comment]
Hi Geidel,

I like the idea of this, but it shouldn't replace the default behavior of inheriting the original filename. I would rather make it configurable, someting like

```php
$uploader->fromSource($foo)
    ->useHashForFilename()
    ->upload();
```

I am away on vacation at the moment, but i will add this to my to-do list when I get home. Otherwise, feel free to iterate on your pr in the meantime.

**Comment by frasmage** [comment]
Hi Geidel,

Great! That is very similar to the approach I was thinking. I have a couple of nitpicks and suggestions to make before we merge this.

- $snake_case for properties please. can we make the  name $hash_filename or similar? Imho, boolean vars shouldn't start with a verb.
- needs a useDefaultFilename() method which clears $filename and $hash_filename properties.
- setFilename() should set $hash_filename to false, e.g. if it is called after.
- useHashForFilename() should clear $filename.
- that line wth the double ternary expression is getting too bloated, needs to be extracted to its own method.
- need to update the documentation accordingly.

Feel free to take a stab at any of those, I'll handle anything that is left over this weekend when I get home.

**Comment by frasmage** [comment]
Looks great! I will update the documentation and push this live with the next version this weekend.

Thanks for your help!

**Comment by geidelguerra** [comment]
Your are welcome! I'll continue trying to improve this awesome library.

**Pull request merged**
