### PR TITLE
Return more granular HTTP status codes for MediaUploadException

### PR DESCRIPTION
**Pull request by sebdesign**
Introduce a `HandlesMediaExceptions` trait which can be used in the
`Exception\Handler` to return more granular HTTP status codes when a
`MediaUploadException` is thrown.

I have updated the docs, (spotted a few typos also), but I couldn't get Sphinx to work.

This can be extended to handle more exceptions like `MediaMoveException` or `MediaUrlException` in the future.

Also it would be interesting if we could throw `Illuminate\Validation\ValidationException`s instead of `HttpException`s in some cases, for better upload validation handling.

### CODE REVIEW

**Comment by frasmage** [comment]
Hi @sebdesign,

That is a fantastic idea!

Before I merge this, I have a slightly different ideal implementation in mind, if you will indulge me. I've had the idea to make the exceptions themselves more granular on the back burner for a while now. Instead of everything throwing a `MediaUploadException` with a different message, throw a number of different exceptions classes that all extend that base class (For example, all of the exceptions that you have under error 415 return a `MediaUploadUnsupportedFileException` with the appropriate message and exception code). 

That way, you don't need to have the huge list of constants and custom error codes to keep track of what is what. It also provides the benefits of making different kinds of errors individually catchable.

Would you like to take a stab at this yourself? Otherwise I am happy to take over and make these changes.

-Sean


PS: I really appreciate that you took the time to update the tests and the docs to go with your work!

**Comment by sebdesign** [comment]
I'm happy you like this idea!

I had the same thought and I agree that the exception could be extracted into more granular exceptions that extend `MediaUploadException`, that way we could get rid of the exception codes and the constants.

Regarding the implementation, those exceptions would extend `MediaUploadException`, but the static constructors would be also inherited. Is that an issue?

I'm willing to take a stab at this, but I'd love that you point me which exceptions should I create beyond `MediaUploadUnsupportedFileExtension`, or how should I group them. I was thinking that each one of the static constructors would have its own exception. Is that overkill?

On the other hand `MediaUploadUnsupportedFileExtension` is not the same if a file extension is unrecognized or restricted, unless they have different messages.

**Comment by frasmage** [comment]
> I was thinking that each one of the static constructors would have its own exception. Is that overkill?

Possibly? Could provide more granularity but that is a ton of classes to juggle and remember. Might be easier to group by theme and use different messages.

> Regarding the implementation, those exceptions would extend `MediaUploadException`, but the static constructors would be also inherited. Is that an issue?

The static constructors should be moved to the most appropriate subclass. The base `MediaUploadException` class would have no methods (should be a 500 error).

> I'm willing to take a stab at this, but I'd love that you point me which exceptions should I create beyond MediaUploadUnsupportedFileExtension, or how should I group them.

I think grouping them by equivalent HTTP status code makes the most sense, as you have already done.

401 -> MediaUploadForbiddenException
404 -> MediaUploadNotFoundException
409 -> MediaUploadFileExistsException
413 -> MediaUploadSizeException
415 -> MediaUploadFileNotSupportedException
422/500 -> MediaUploadConfigurationException

The ones you have listed under 422 should probably all be 500 errors, since they imply misconfiguration on the developer's part, not a user error.


> On the other hand MediaUploadUnsupportedFileExtension is not the same if a file extension is unrecognized or restricted, unless they have different messages.

Yes, each case should continue to provide the same message.

Also, forgot to address these in your initial post:

>This can be extended to handle more exceptions like MediaMoveException or MediaUrlException in the future.

Those both imply a server/configuration error rather than a user error, so I am fine with those remaining 500 errors. They could possibly be made more granular, but I think both have so few exception cases that this isn't necessary yet.

> Also it would be interesting if we could throw Illuminate\Validation\ValidationExceptions instead of HttpExceptions in some cases, for better upload validation handling.

I like that in concept, though we don't explicitly receive a `Request` object at any point, so transforming to that is not necessarily correct. For example, this could make sense if the developer does `MediaUploader::fromSource($request->file($foo));` but doesn't when the source isn't part of the request at all. I would nix this idea for now.

**Comment by sebdesign** [comment]
Hi @frasmage, I've pushed a commit with the changes we discussed.

Along with that, I noticed that the `MediaMoveException` is thrown in the same context with the `MediaExistsException`. It's always when a file already exists where it shouldn't. So I replaced it, and used the `MediaMoveException` in the case that `move` fails for any other reason. 

Unfortunately I couldn't think of a test case where this exception could be thrown, but I believe it's good to be there instead of saving the media and returning. I tried to make the target directory not writable, to check that the `move` would return false and the exception would be thrown, but instead of that I got an `ErrorException`, which Laravel throws when PHP triggers an error.
Maybe it would be safe to wrap the `move` statement in a `try` block and throw the `MediaMoveException` in the `catch` block?

Also, a few more typos were fixed in the docs. :)

**Comment by frasmage** [comment]
Hi @sebdesign,

Making progress. I still have a few requests.

- First is a naming nitpick, because that is always a challenge. can we prefix all of the Exception classes with `MediaUpload` instead of just `Media`. This seems more accurate: it isn't the `Media` that is misconfigured, it is the uploader. It also makes it clearer that the class is a subset of MediaUploadException. The names I listed in my previous post are about as semantically meaningful as I can think of. Also, MediaUpload**File**NotFoundException, it is the file which is missing or unreadable, not the media (as in the model) or the uploader.

- Instead of having a list of constants mapping codes for each class, why not just populate the `$code` property of the Exception class, either on initialization or through the constructor and then read that in the handler? For example:

```
class MediaUploadFileNotFoundException extends MediaUploadException
{
    protected $code = 404;

    // OR

    public static function fileNotFound($path)
    {
        return new static("File `{$path}` does not exist.", 404);
    }
}
```

- I think I prefer the "file exists" case for upload and move each throwing different exception classes. I don't think it makes sense for the `Media::move` operation to throw a subclass of `MediaUploadException`, since the operation has nothing to do with the uploader. Makes it clearer to catch if they are separated. Also, changing the base class here would be a BC break, in case anyone was catching this case in their code.
  
- I am aware that PHP or Flysystem will already throw an ErrorException if there is a permission error during the move operation. I am ok with that not being caught directly, but I can see merits to catching and rethrowing a MediaMoveException so that either case can be caught. 

  If we do that though, we should probably split into two subclasses `MediaMoveFileExistsException` (which could be handled to move elsewhere) and `MediaMoveWriteException` (which is harder to handle in code). The latter should probably imply that file permissions are the issue, though I imagine available disk space could also be a factor. Perhaps forward the original error message?

  I am still debating this one, this error is occurring at a much lower level, I am not sure if the package should take responsibility

**Comment by sebdesign** [comment]
Hi @frasmage,
I'm currently working on your requests. Do you think putting all those exceptions under a `MediaUpload` namespace is better than prefixing the class name? E.g. `Plank\Mediable\Exceptions\MediaUpload\FileNotFoundException`? It looks accurate to me.

**Comment by sebdesign** [comment]
Regarding the mapping of the status codes, I don't think that the exception should be aware of the HTTP status code it is associated. This is something closer to the HTTP layer than the error handling layer. I'm all for separation of concerns, so that's why it's the trait's responsibility to handle this aspect. Let me know your thoughts about this.

**Comment by frasmage** [comment]
Hi @sebdesign,

>Do you think putting all those exceptions under a `MediaUpload` namespace is better than prefixing the class name?

I'm ok with that. Only one we have to be careful with is the base `MediaUploadException` which would be a BC break if we move it. That could certainly happen, but it would mean this feature would only be launched along with 3.0. 

> Regarding the mapping of the status codes, I don't think that the exception should be aware of the HTTP status code it is associated. This is something closer to the HTTP layer than the error handling layer. I'm all for separation of concerns, so that's why it's the trait's responsibility to handle this aspect. Let me know your thoughts about this.

That is a valid point. Ok, lets leave them separated.

**Comment by sebdesign** [comment]
Reflecting on the `HandlesMediaExceptions` trait, it could be even used on a controller, not only on the `ExceptionHandler`. E.g.:

```php
<?php

namespace App\Http\Controllers;

class MediaController
{
    use HandlesMediaExceptions;

    public function store(Request $request)
    {
        try {
            MediaUpload::fromSource($request->file('image'))
            // do your configuration/validation
            ->upload();
        } catch(MediaUploadException $e) {
            // maybe rename this method to `transformToHttpException`?
            throw $this->prepareMediaUploadException($e);
        }
    }
}
```

**Comment by frasmage** [comment]
Interesting. I like the fine grained control that would provide, allowing controllers to behave differently. I'm a little worried that `transformToHttpException()` is a bit too generic a name, maybe `transformMediaUploadException()`?

I'll give your PR a final look over tomorrow.

**Comment by frasmage** [comment]
Hey @sebdesign,

After making a few minor tweaks (renaming stuff, adjusting the traits behaviour, adding to docs), I have merged this and release a new minor version with your additions.

Thank you very much for your contribution!

**Comment by sebdesign** [comment]
Hi @frasmage,

Thank you for merging this and for your attentive feedback!

I also made a source adapter and a source class for importing media from file contents as a string. E.g. in my case I used this to import a file from the stdout of a CLI command (like ffmpeg) which was executed with a symfony process. If you are interested I can send a PR.

Cheers!

**Comment by frasmage** [comment]
@sebdesign Please do! It may or may not be something that I decide should be included in the core package, but I am always happy to see what people are working on to foster new ideas.

**Pull request merged**
