### PR TITLE
Support Mongodb

### PR DESCRIPTION
**Pull request by simonschaufi**
I'm using Mongodb and every model needs to extend `\Jenssegers\Mongodb\Eloquent\Model`. I found this solution here: https://stackoverflow.com/a/17325203

### CODE REVIEW

**Comment by frasmage** [comment]
Hi @simonschaufi,

Unfortunately, this is not a pull request that I can accept.

Laravel's [query builder](https://laravel.com/docs/5.4/database#introduction) does not support MongoDB out of the box. I am not comfortable depending on a arbitrary third party library for this.

Your middleman class solution is a problematic (and a bit hacky for my tastes). It would make Media _always_ use MongoDB if that library was installed, even if it is only being used for other things.

I would recommend forking this package and making Media extend the MongoDB model directly.

**Comment by simonschaufi** [comment]
ok. It would have been nice to support both but I will continue in a fork.

Could you then instead link to my package for other people to see that my fork supports Mongodb?

**Comment by frasmage** [comment]
I will keep your fork in mind if anyone else asks about mongo support :)

**Comment by simonschaufi** [comment]
Here is my mongodb supported branch: https://github.com/simonschaufi/laravel-mediable/tree/mongodb

**Pull request closed without merging**
