### PR TITLE
Update MediaUploader.php

### PR DESCRIPTION
**Pull request by ryankilf**
Ability to upload & replace existing items

### CODE REVIEW

**Comment by frasmage** [comment]
Hey @ryankilf,

The nullable typehint you included is PHP 7.1+, though the 2.x branch of this package is compatible with PHP 5.6+.

An implementation of this has already been added to the 3.0 branch (see `onDuplicateReplace()`, it now behaves differently). If you need this for your project, you can load that branch from composer with "dev-3.0".

**Comment by ryankilf** [comment]
Hi Fras,

Thank you forgetting back to me.

You're, of course quite right to close this PR without merging due to the CI failures on php 7 / 5.6. I didn't realise you required support for 7/5.6 and used my failure as an example of CI working well in a talk in work this morning!

 My understanding of onDuplicateReplace is that it will replace, if the media filename is the same as a previous item. 

I'm hoping to replace the media associated with the record with  a new file which may have a _separate_ filename. Does that make sense? Is there a technique for doing that which will work?

**Comment by frasmage** [comment]
Yes, `onDuplicateReplace()` currently deletes the old record and creates a new media record (new id). In the 3.0 branch that behaviour has been renamed `onDuplicateDelete()` and the replace action now overwrites the file and updates the existing media record (same id).

I curious why you need to use an existing media record and also change its directory at once. What is the use case of this? I understand the need for the replace/update behaviour to maintain existing relationships, but not changing its location as well. 

Is this something that could simply be done in two steps, i.e.

``` 
$media = $uploader->toDestination($media->disk, $media->directory)
->onDuplicateReplace()
->upload();

$media->move($newDirectory);
```

**Comment by frasmage** [comment]
Is your intention to keep the original file, even though it is being disconnected from its mediable relationships? If that is the case you might be better served by uploading the file on its own to the new location then writing a query to update the `mediables` pivot table to change the media_id from your old media's id to the new one of all. This way you would still be able to keep the original file and media record for posterity.

**Pull request closed without merging**
