### PR TITLE
Added alt field

### PR DESCRIPTION
**Pull request by zmilad97**
Added "ALT" field for medias , I customize the Mediable for every project of mine so i decide to open a pull request  , it is so useful  for images and videos on websites . Please consider it .

### CODE REVIEW

**Comment by smdm22** [comment]
**just what i needed ty**

**Comment by frasmage** [comment]
Hello, seems like a common enough use case to consider. Database migration changes require a major version bump. Since this is a convenience addition for something that is easily done manually, I will delay merging this into the core package until we have other compelling reasons to release a new major version

**Comment by selfsimilar** [comment]
Seconding this. For accessibility reasons it's really important to have alt text for images, and adding a default field to support is only a good thing.

**Comment by violetaStk** [comment]
Is this going to be merged any time soon ?

**Comment by frasmage** [comment]
implemented in upcoming major version (#343) with a more complete solution, including MediaUploader helpers.

**Comment by frasmage** [comment]
Version 6.0.0 has been released.

**Pull request closed without merging**
